from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views # Import the views module

app_name = 'users' # Defines the namespace

# Create a router instance
# DefaultRouter includes a default API root view and format suffix patterns.
# Use SimpleRouter if you don't need the API root view.
router = DefaultRouter()

# Register the UserViewSet with the router
# The first argument is the URL prefix for this viewset ('users')
# The second argument is the ViewSet class itself
# The third argument is the base name for the generated URL patterns ('user')
router.register(r'users', views.UserViewSet, basename='user')

# The router automatically generates the following URLs (among others):
# /api/users/          (GET: list users, POST: create user - if ModelViewSet) -> maps to 'user-list' name
# /api/users/{pk}/     (GET: retrieve user, PUT/PATCH: update, DELETE: delete - if ModelViewSet) -> maps to 'user-detail' name
# /api/users/me/       (GET, PUT, PATCH for the custom action) -> maps to 'user-me' name

urlpatterns = [
    # Include the URLs generated by the router
    path('', include(router.urls)),
]